### ISSUE TITLE
 Change Selection Text Color to Match Website Theme

### ISSUE THREAD

**Issue by AasheeshLikePanner** [Kleo-Network/frontend#15]
Description:
The current selection text color uses the default blue, which doesn't align with the website's overall theme and design aesthetics. This inconsistency can detract from the cohesive look and feel of the site. Changing the selection text background and text color to match the website's theme will enhance visual consistency, create a more engaging user experience, and make selected text stand out in a way that feels intentional and eye-catching.

Proposed Solution:
Modify the selection text color to use colors that align with the website’s theme.
Utilize Tailwind CSS selection classes (e.g., selection:bg-themeColor and selection:text-themeTextColor) to customize the appearance of selected text.
Ensure that the new selection colors maintain readability and complement the existing design elements of the site.
Benefits:
Creates a cohesive design experience that aligns with the site's theme.
Enhances the aesthetics and makes the site feel more polished.
Improves user interaction by making text selection more visually appealing.

Before:

https://github.com/user-attachments/assets/c385a1e2-8c0b-49f2-8135-ec49c299647e

After:

https://github.com/user-attachments/assets/1df47705-75ed-4029-8332-b7d06cdd902b

**Comment by vaibhavgeek** [comment]
Thank you for bringing this issue to our attention and for submitting the pull request to address it, AasheeshLikePanner. I appreciate your effort to improve the visual consistency of our website.
I'm pleased to inform you that I've reviewed and merged the pull request (#16) that changes the selection color to match our website's theme. This enhancement will indeed create a more cohesive design experience and improve the overall aesthetics of our site.
As the proposed solution has been implemented, I'm now closing this issue. Thank you again for your contribution to improving our user interface.
