### ISSUE TITLE
Enhance Paragraph Readability: Update Font for Improved Appearance

### ISSUE THREAD

**Issue by AasheeshLikePanner** [Kleo-Network/frontend#17]
## Description

The current font used for paragraphs on the website is not meeting readability standards and affects the overall visual appearance of the text. The font appears cluttered and makes it difficult for users to read and engage with the content.

## Problem

- **Readability**: The current font size and style make the text hard to read, especially on smaller screens or devices with varying resolutions.
- **Visual Consistency**: The font choice does not align well with the rest of the website's design, creating a disjointed user experience.
- **User Experience**: The lack of readability and poor appearance detract from the overall user experience, potentially affecting user engagement and satisfaction.

## Proposed Solution

- **Font Selection**: Update the paragraph font to a more readable and aesthetically pleasing typeface. Consider fonts that are clean, modern, and widely used for body text to enhance legibility.
- **Font Size and Line Spacing**: Adjust the font size and line spacing to ensure that the text is easy to read and not too cramped.
- **Consistency**: Ensure the new font aligns with the website's overall design and maintains a consistent look and feel across all text elements.

## Benefits

- **Improved Readability**: Users will find it easier to read and engage with the content, leading to a better overall experience.
- **Enhanced Aesthetics**: A more appropriate font will improve the visual appeal of the website and create a more polished and professional look.
- **Better User Engagement**: Readable and well-presented text can increase user engagement and time spent on the site.

## Screenshots
![image](https://github.com/user-attachments/assets/49c1ebfe-1452-44cd-906c-a82a6b0d4fc0)

Thank you for considering this update. Looking forward to your feedback!

**Comment by vaibhavgeek** [comment]
Awesome Work, Closing this issue!
