### ISSUE TITLE
Bounty 1 - Integrate smart contracts with existing frontend.

### ISSUE THREAD

**Issue by vaibhavgeek** [Kleo-Network/frontend#2]
Integrate smart contracts with existing frontend.

**Comment by visitskyworld** [comment]
Hi @vaibhavgeek I am interested in this bounty

**Comment by vaibhavgeek** [comment]
Hey @visitskyworld bounties are not open yet, please join our discord and we will announce when they do. Also, this specific bounty can happen only after smart contract bounties are completed. :)

**Comment by visitskyworld** [comment]
Thanks, @vaibhavgeek can I start working on other frontend bounties then?

**Comment by vaibhavgeek** [comment]
Bounties aren't open yet. @visitskyworld
