### ISSUE TITLE
[Styled Hero Section] Kleo Network Update Hero Section 

### ISSUE THREAD

**Issue by vaibhavgeek** [Kleo-Network/frontend#23]
Here's a bounty description for changing the font and design elements according to the Figma prototype:

---

### Bounty: Update Font and UI Elements to Match Figma Design (50 USDC)

**Project:** Kleo

**Bounty Amount:** 50 USDC

**Task:**  
We are looking for a developer/designer to update the font and design elements to match the specifications provided in our Figma prototype. The objective is to ensure that the interface aligns perfectly with the visual style and design guidelines set in the Figma link below:

**Figma Prototype:** https://www.figma.com/proto/JN3XzNNAqf1HeH1B0x4sl6/KLEO-Design-system?node-id=3146-4603&node-type=frame&t=EBKKj03OWTrd3Wpm-0&scaling=min-zoom&content-scaling=fixed&page-id=111%3A4368&starting-point-node-id=819%3A3948

**Requirements:**  
1. Update the font to match the specified typography in the Figma design.
2. Ensure all UI elements, including buttons, headings, and text fields, align with the Figma prototype.
3. Implement any additional style adjustments (e.g., color, spacing) as shown in the design.

**Submission:**  
- Please provide screenshots of the updated interface alongside the Figma design for comparison.
- Ensure that the changes are consistent across all relevant pages/screens.

**Deadline:**  21 October

**Comment by JainamShah28** [comment]
@vaibhavgeek I will work on this issue.

**Comment by JainamShah28** [comment]
@vaibhavgeek The [PR](https://github.com/Kleo-Network/frontend/pull/24) for these changes has been merged, can we close this issue?

**Comment by vaibhavgeek** [comment]
Closing this, awesome work @JainamShah28
