### ISSUE TITLE
Bounty 2 - Create button sizing, cookie popup manager

### ISSUE THREAD

**Issue by vaibhavgeek** [Kleo-Network/frontend#3]
Allow organizations to choose from multiple templates, and allow them to change the 

1. Size of buttons 
2. Color of text 
3. Size of text
4. Size of outside box 
5. Text on the popup (Except a compulsory text) 
6. Color of text 
7. Background color of buttons 

Few examples of how the popup would look like, based on user preferences. 

![Screenshot 2023-07-06 at 6 41 19 PM](https://github.com/Kleo-Network/frontend/assets/1227925/44007ccb-1294-4d1e-93eb-1fda3a8eca30)
![Screenshot 2023-07-06 at 6 42 01 PM](https://github.com/Kleo-Network/frontend/assets/1227925/e2b75dff-dc52-4028-b49e-0e4d11233bb6)
![Screenshot 2023-07-06 at 6 41 46 PM](https://github.com/Kleo-Network/frontend/assets/1227925/e217900a-9dae-4413-84da-fed052bf9845)

**Comment by Wholesomebruh** [comment]
Hi @vaibhavgeek , Please explain the issue here. Is decision still pending from organisations or what it is specifically? Thank you

**Comment by vaibhavgeek** [comment]
This is being done by @aish96

**Comment by aish96** [comment]
I'll be adding the cookie-manager pop-up step to the kleo application, had a discussion with @vaibhavgeek today regarding the requirements.
